dist: trusty
sudo: true
language: cpp
compiler: clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

script:
  - make
  - ./unit-test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "CodeCov Error"

notifications:
  email: false

